### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by KorySchneider**
Initial documentation. All components completed thus far have been covered.

### CODE REVIEW

**Comment by jonmpqts** [comment]
Nice! Looks really good. Might put a link to the `docs` directory in the main `README.md`. Also, a `README.md` in `docs` with a summary might be nice as well.

**Comment by jonmpqts** [comment]
Just noticed you have `SidebarToggle` and `UserPanelImage` stuff mixed in. Was that intentional?

**Comment by KorySchneider** [comment]
Thanks :^)
Good thinking, I'll add a link to the docs in the root `README.md` and add a readme in `docs/`.

`SidebarToggle` should not be in `sidebar.md`, my mistake. It should go in `main-header.md`, but first I suppose I should actually write the component haha.

**Comment by jonmpqts** [comment]
Once this is rebased with master it's squash and merge city.

**Pull request merged**
